/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HexApi } from "../../..";
import * as core from "../../../core";

export const ProjectRunStatus: core.schemas.Schema<ProjectRunStatus.Raw, HexApi.project.ProjectRunStatus> = core.schemas
  .string()
  .transform<HexApi.project.ProjectRunStatus>({
    parse: (value) => HexApi.project.ProjectRunStatus._parse(value),
    json: ({ value }) => value,
  });

export declare namespace ProjectRunStatus {
  type Raw = string;
}
