/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HexApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const ProjectStatusResponsePayload: core.schemas.ObjectSchema<
  ProjectStatusResponsePayload.Raw,
  HexApi.project.ProjectStatusResponsePayload
> = core.schemas.object({
  projectId: core.schemas.string(),
  runId: core.schemas.string(),
  runUrl: core.schemas.string(),
  status: core.schemas.lazy(() => serializers.project.ProjectRunStatus),
  startTime: core.schemas.date(),
  endTime: core.schemas.date(),
  elapsedTime: core.schemas.number(),
  traceId: core.schemas.string(),
});

export declare namespace ProjectStatusResponsePayload {
  interface Raw {
    projectId: string;
    runId: string;
    runUrl: string;
    status: serializers.project.ProjectRunStatus.Raw;
    startTime: string;
    endTime: string;
    elapsedTime: number;
    traceId: string;
  }
}
