/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HexApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const ProjectRunsResponse: core.schemas.ObjectSchema<
  ProjectRunsResponse.Raw,
  HexApi.project.ProjectRunsResponse
> = core.schemas.object({
  runs: core.schemas.list(core.schemas.lazyObject(() => serializers.project.ProjectStatusResponsePayload)),
  nextPage: core.schemas.string(),
  previousPage: core.schemas.string(),
  traceId: core.schemas.string(),
});

export declare namespace ProjectRunsResponse {
  interface Raw {
    runs: serializers.project.ProjectStatusResponsePayload.Raw[];
    nextPage: string;
    previousPage: string;
    traceId: string;
  }
}
