/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HexApi } from "../../..";
import * as core from "../../../core";

export const RunProjectResponse: core.schemas.ObjectSchema<RunProjectResponse.Raw, HexApi.project.RunProjectResponse> =
  core.schemas.object({
    projectId: core.schemas.string(),
    runId: core.schemas.string(),
    runUrl: core.schemas.string(),
    runStatusUrl: core.schemas.string(),
    traceId: core.schemas.string(),
  });

export declare namespace RunProjectResponse {
  interface Raw {
    projectId: string;
    runId: string;
    runUrl: string;
    runStatusUrl: string;
    traceId: string;
  }
}
