/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HexApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const RunProjectRequest: core.schemas.ObjectSchema<RunProjectRequest.Raw, HexApi.project.RunProjectRequest> =
  core.schemas.object({
    inputParams: core.schemas.lazyObject(() => serializers.project.InputParameters),
  });

export declare namespace RunProjectRequest {
  interface Raw {
    inputParams: serializers.project.InputParameters.Raw;
  }
}
