/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HexApi } from "../../..";

export interface ProjectStatusResponsePayload {
  /** Unique ID for a Hex project. This can be found in the Variables side bar of the Logic View of a project, or by visiting the Project, and copying the UUID after hex in the URL. */
  projectId: string;
  /** Unique ID for a run of a Hex project */
  runId: string;
  /** URL to view the current progress of the project run in the Hex UI */
  runUrl: string;
  /** Current status of a project run */
  status: HexApi.project.ProjectRunStatus;
  /** UTC timestamp of when the project run started */
  startTime: Date;
  /** UTC timestamp of when the project run ended */
  endTime: Date;
  /** Total elapsed time for the project run in milliseconds */
  elapsedTime: number;
  /** A unique identifier for this API request. The Hex Support team may request this value when debugging an issue. */
  traceId: string;
}
