/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HexApi } from "../../..";

export interface ProjectRunsResponse {
  /** Array of run status payloads in the same format returned by the GetRunStatus endpoint */
  runs: HexApi.project.ProjectStatusResponsePayload[];
  /** URL to fetch the next page of results for a paginated API request */
  nextPage: string;
  /** URL to fetch the next page of results for a paginated API request */
  previousPage: string;
  /** A unique identifier for this API request. The Hex Support team may request this value when debugging an issue. */
  traceId: string;
}
