/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface RunProjectResponse {
  projectId: string;
  runId: string;
  runUrl: string;
  runStatusUrl: string;
  traceId: string;
}
