/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HexApi } from "../../..";

export interface RunProjectRequest {
  /**
   * Optionally specify input parameters for this project run. These should be structured as a dictionary of key/value pairs, where the key name matches the name of the variable in the Hex project.
   * Only parameters that are added to the published app can be set via this request parameter. Any additional inputs will be ignored.
   * If no input parameters are provided, the project will be run with the default input values. Note that if input parameters are provided, this run will not be able to update the cached values for the project, and the updateCache setting (below) will be ignored.
   *
   */
  inputParams: HexApi.project.InputParameters;
}
