/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as ProjectClient } from "./resources/project/client/Client";

export declare namespace HexApiClient {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      token?: core.Supplier<core.BearerToken>;
    };
  }
}

export class HexApiClient {
  constructor(private readonly options: HexApiClient.Options) {}

  #project: ProjectClient | undefined;

  public get project(): ProjectClient {
    return (this.#project ??= new ProjectClient(this.options));
  }
}
