/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  /**
   * For most Hex users.
   * Single-tenant app users should replace the app.hex.tech part of this URL with the URL they use to access Hex (e.g. atreides.hex.tech).
   *
   */
  Production: "https://app.hex.tech/api/v1",
} as const;

export type Environment = typeof Environment.Production;
